name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Determine BASE_PATH for GitHub Pages
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "BASE_PATH=/" >> $GITHUB_ENV
          else
            echo "BASE_PATH=/$REPO_NAME/" >> $GITHUB_ENV
          fi

      - name: Build
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
        run: |
          echo "Using BASE_PATH=$BASE_PATH"
          yarn build

      - name: Add SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
