name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages-branch"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Determine BASE_PATH for GitHub Pages
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "BASE_PATH=/" >> $GITHUB_ENV
          else
            echo "BASE_PATH=/$REPO_NAME/" >> $GITHUB_ENV
          fi

      - name: Build
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
        run: |
          echo "Using BASE_PATH=$BASE_PATH"
          yarn build

      - name: Add SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
